version: "3"

services:
  anycat:
    image: swr.cn-south-1.myhuaweicloud.com/xiaozuo7/anycat:v1
    container_name: anycat
    network_mode: "host"
    volumes:
      - /home/docker_volume/anycat/logs:/app/logs

  nginx-proxy:
    image: swr.cn-south-1.myhuaweicloud.com/xiaozuo7/nginx-proxy:v1
    container_name: nginx-proxy
    network_mode: "host"
    volumes:
    - /home/docker_volume/ssl:/etc/nginx/ssl

