version: "3"

services:
  anycat:
    image: swr.cn-south-1.myhuaweicloud.com/xiaozuo7/anycat:v1
    container_name: anycat
    networks:
      - my-network
    volumes:
      - /home/docker_volume/anycat/config.yaml:/app/config.yaml
      - /home/docker_volume/anycat/logs:/app/logs

  nginx-proxy:
    image: swr.cn-south-1.myhuaweicloud.com/xiaozuo7/nginx-proxy:v1
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge